### ISSUE TITLE
UnsupportedOperationException Uri

### ISSUE THREAD

**Issue by kkoshin** [foodiestudio/sugar#11]
通过 Open Document Tree 方式获取到的 uri，无法查询路径

```
 java.lang.UnsupportedOperationException: Unsupported Uri content://com.android.externalstorage.documents/tree/primary%3ADocuments%2Fdonut
         at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:174)
         at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
         at android.content.ContentProviderProxy.query(ContentProviderNative.java:481)
         at android.content.ContentResolver.query(ContentResolver.java:1245)
         at android.content.ContentResolver.query(ContentResolver.java:1171)
         at android.content.ContentResolver.query(ContentResolver.java:1127)
         at com.github.foodiestudio.sugar.saf.SAFHelperKt.fetchMetadataFromDocumentProvider(SAFHelper.kt:159)
```

**Comment by kkoshin** [comment]
document 相关的操作需要使用 `androidx.documentfile` 这个库来操作。

比如上面拿到的 document tree 是一个文件夹，想要在这个文件夹下创建文件夹、文件，需要先转成 DocumentFile

```kotlin
val pickedUri = "content://com.android.externalstorage.documents/tree/primary%3ADocuments%2Fdonut"
val documentFile = DocumentFile.fromTreeUri(context, pickedUri) 
val file = documentFile.createFile("video/mp4", "foo.mp4") // 返回依然是个 DocumentFile 类型，后续可以对这个文件写入
val uri = file.getUri() // 拿到 uri，充当 path，然后拿到 outputStream 
```

**Comment by kkoshin** [comment]
- https://developer.android.com/about/versions/oreo/android-8.0?hl=zh-cn#ptd
- https://stackoverflow.com/questions/48915273/is-there-a-straightforward-way-to-get-the-parent-directorys-uri-from-a-file-uri

**Comment by kkoshin** [comment]
尽可能使用 Scoped Storage 的方式处理文件。并不是所有场景都要追求 filePath，记录一个 document uri 也是够了的
